import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0d2818", // Darker, richer green for depth
    position: "relative",
  },
  backgroundElements: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
    zIndex: 0,
  },
  circle1: {
    position: "absolute",
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    top: -100,
    right: -100,
  },
  circle2: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(255, 255, 255, 0.015)",
    bottom: 50,
    left: -50,
  },
  circle3: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    top: "35%",
    right: 30,
  },
  mushroomContainer1: {
    position: "absolute",
    top: 60,
    left: -140,
    width: 300,
    height: 300,
    opacity: 0.15,
    transform: [{ rotate: "-50deg" }],
  },
  mushroomContainer2: {
    position: "absolute",
    bottom: 60,
    right: -120,
    width: 280,
    height: 280,
    opacity: 0.08,
    transform: [{ rotate: "20deg" }],
  },
  mushroom: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
    tintColor: "rgba(255, 255, 255, 0.7)",
  },
  plateContainer: {
    position: "absolute",
    bottom: -140,
    right: -100,
    width: 340,
    height: 340,
    opacity: 0.6,
    transform: [{ rotate: "15deg" }],
  },
  plate: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  keyboardView: {
    flex: 1,
    zIndex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 28,
    paddingBottom: 100,
  },
  logoContainer: {
    marginBottom: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  logoFrame: {
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.15)",
    shadowColor: "#fff",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 8,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "visible",
  },
  subtitleContainer: {
    marginTop: 6,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  subtitleText: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.75)",
    fontWeight: "600",
    letterSpacing: 3,
    textTransform: "uppercase",
    textAlign: "center",
  },
  logo: {
    width: 140,
    height: 140,
    resizeMode: "contain",
    zIndex: 1,
  },
  welcomeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    width: "100%",
    maxWidth: 320,
  },
  welcomeLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    marginHorizontal: 16,
  },
  welcomeText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#fff",
    textAlign: "center",
    letterSpacing: 1.5,
    opacity: 0.98,
    textShadowColor: "rgba(255, 255, 255, 0.3)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  formContainer: {
    width: "100%",
    maxWidth: 360,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
    paddingLeft: 6,
  },
  inputLabel: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.85)",
    fontWeight: "600",
    letterSpacing: 0.8,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderRadius: 20,
    borderColor: "rgba(255, 255, 255, 0.2)",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    paddingHorizontal: 20,
    minHeight: 60,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
    // Glassmorphism effect
    overflow: "hidden",
  },
  inputIcon: {
    marginRight: 14,
    opacity: 0.8,
  },
  input: {
    flex: 1,
    paddingVertical: 18,
    fontSize: 16,
    color: "#fff",
    backgroundColor: "transparent",
    letterSpacing: 0.5,
    fontWeight: "500",
  },
  eyeIcon: {
    padding: 8,
  },
  forgotPassword: {
    alignSelf: "flex-end",
    marginBottom: 24,
    marginTop: 4,
  },
  forgotPasswordText: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.9)",
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  registerPrompt: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginBottom: 16,
    padding: 14,
    backgroundColor: "rgba(255, 193, 7, 0.15)",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "rgba(255, 193, 7, 0.4)",
    shadowColor: "#ffc107",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  registerPromptText: {
    fontSize: 14,
    color: "#fff",
    textAlign: "center",
  },
  registerLink: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  primaryButton: {
    backgroundColor: "#fff",
    borderRadius: 22,
    padding: 20,
    width: "100%",
    marginTop: 12,
    shadowColor: "#fff",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 12,
    overflow: "hidden",
    // Shiny effect
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  buttonShineOverlay: {
    position: "absolute",
    top: 0,
    left: "-100%",
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.4)",
    transform: [{ skewX: "-20deg" }],
  },
  buttonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    zIndex: 1,
  },
  primaryButtonText: {
    color: "#0d2818",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  buttonArrowContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(13, 40, 24, 0.15)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0d2818",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 32,
    flexWrap: "wrap",
  },
  footerText: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: "500",
  },
  footerLink: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "700",
    marginLeft: 6,
    textShadowColor: "rgba(255, 255, 255, 0.2)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  backButton: {
    position: "absolute",
    top: 10,
    left: 20,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
});
